# Generated by Django 6.0.3 on 2026-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untappd_username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('products_processed', models.IntegerField(default=0)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('handle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_url', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('abv', models.FloatField(blank=True, db_index=True, null=True)),
                ('ibu', models.IntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, db_index=True, max_length=100)),
                ('untappd_style', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('untappd_url', models.URLField(blank=True, max_length=500)),
                ('untappd_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('untappd_rating_count', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(db_index=True, default=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('style_category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('country_region', models.CharField(blank=True, db_index=True, max_length=50)),
                ('price_bucket', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-untappd_rating', '-untappd_rating_count'],
                'indexes': [models.Index(fields=['style_category', 'in_stock'], name='recommendat_style_c_cdbab2_idx'), models.Index(fields=['country', 'in_stock'], name='recommendat_country_79edef_idx'), models.Index(fields=['abv', 'in_stock'], name='recommendat_abv_a3e8a7_idx')],
            },
        ),
    ]
