# Generated by Django 6.0.3 on 2026-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
