# Generated by Django 6.0.3 on 2026-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_add_is_active_to_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='variant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
