# Generated by Django 6.0.3 on 2026-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_add_profile_type_to_cachedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='inhoud',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='beer',
            name='rijpingsmethode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
