# Generated by Django 6.0.3 on 2026-08-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_beer_inhoud_beer_rijpingsmethode'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='merk',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beer',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
